INPUT_PATH: input/LIB15/ANI_MTDNA_VEG/
OUTPUT_PATH: output/LIB15/
OUTPUT_FILENAME: LIB15_INDIV
REMOVE_PRIMERS: FALSE
THREADS: 10
CONDA_SOURCE: /home/bioinfo/miniconda3/etc/profile.d/conda.sh
TAX_DATABASE_PATH: /media/bioinfo/6tb_hdd/04_Blast_Databases/taxdb
BLAST_DATABASE_PATH:  /media/bioinfo/6tb_hdd/04_Blast_Databases/new_nt/nt # nt or 16s
CLUSTERING_PARAMS:
  aL: 0.8 # 0.8
  aS: 0.8 # 0.8
  c: 0.7 # 0.7
MIN_SEQS_FOR_CONSENSUS: 5 # 5
HIERARCHY_DATABASE:
  HOST: localhost
  USER: root
  PASSWORD: Amora#1000
  DATABASE: ncbi_data
