INPUT_PATH: input/LIB11_2/input_others/
OUTPUT_PATH: output/LIB11_2/output_others/
OUTPUT_FILENAME: RESIST_LIB11
CLUSTERS2PROCESS: 200
REMOVE_PRIMERS: FALSE
THREADS: 14
CONDA_SOURCE: /home/bioinfo/miniconda3/etc/profile.d/conda.sh
TAX_DATABASE_PATH: '/media/bioinfo/6tb_hdd/04_Blast_Databases/taxdb'
BLAST_DATABASE_PATH:  /media/bioinfo/6tb_hdd/04_Blast_Databases/new_nt/nt # nt or 16s
CLUSTERING_PARAMS:
  aL: 0.98 # 0.8
  aS: 0.98 # 0.8
  c: 0.98 # 0.7
MIN_SEQS_FOR_CONSENSUS: 0 # 5
HIERARCHY_DATABASE:
  HOST: localhost
  USER: root
  PASSWORD: Amora#1000
  DATABASE: ncbi_data
